export type AppNavItem = {
  id: string
  title: string
  description: string
  path: string
  icon: string
}

export const navItems: AppNavItem[] = [
  {
    id: 'agents',
    title: 'AI Agents',
    description: 'No-code agent builder, workflows, automation, memory and observability.',
    path: '/agents',
    icon: '🤖',
  },
  {
    id: 'chat',
    title: 'AI Workspace',
    description: 'Daily conversation workspace with multi-provider chat and sessions.',
    path: '/chat',
    icon: '💬',
  },
  {
    id: 'profile',
    title: 'Profile',
    description: 'Manage account profile, password, and connected devices.',
    path: '/profile',
    icon: '👤',
  },
  {
    id: 'auth',
    title: 'Authentication',
    description: 'Register accounts, login, OTP, and device sessions.',
    path: '/auth',
    icon: '🔐',
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Overview of SRG activity and health.',
    path: '/dashboard',
    icon: '📊',
  },
  {
    id: 'projects',
    title: 'Projects',
    description: 'Manage your workspaces and tasks.',
    path: '/projects',
    icon: '🗂️',
  },
  {
    id: 'knowledge-center',
    title: 'Knowledge Center',
    description: 'Browse documentation and reference guides.',
    path: '/knowledge-center',
    icon: '📚',
  },
  {
    id: 'business-policy',
    title: 'Business Policy',
    description: 'Define enterprise policy, coefficients, supplies, labor and simulations.',
    path: '/business-policy',
    icon: '🏢',
  },
  {
    id: 'devis',
    title: 'Devis',
    description: 'Create quotes and generate billing documents from one engine.',
    path: '/devis',
    icon: '🧾',
  },
  {
    id: 'project-execution',
    title: 'Project Execution',
    description: 'Manage industrial execution, contracts, teams, planning and risks end-to-end.',
    path: '/project-execution',
    icon: '🏗️',
  },
  {
    id: 'procurement-inventory',
    title: 'Procurement & Inventory',
    description: 'Run enterprise purchasing, tenders, suppliers, stock and logistics in one workspace.',
    path: '/procurement-inventory',
    icon: '📦',
  },
  {
    id: 'maintenance',
    title: 'Maintenance',
    description: 'Manage enterprise assets, interventions, planning, technicians, spare parts and intelligent CMMS workflows.',
    path: '/maintenance',
    icon: '🛠️',
  },
  {
    id: 'finance',
    title: 'Finance',
    description: 'Enterprise accounting, finance and management control workspace.',
    path: '/finance',
    icon: '💼',
  },
  {
    id: 'accounting',
    title: 'Comptabilité',
    description: 'General accounting, journals, ledger, balances, entries and closing workflows.',
    path: '/accounting',
    icon: '📒',
  },
  {
    id: 'treasury',
    title: 'Trésorerie',
    description: 'Banks, cash, accounts, transfers, reconciliations and treasury forecasts.',
    path: '/treasury',
    icon: '🏦',
  },
  {
    id: 'finance-customers',
    title: 'Clients',
    description: 'Customer accounting: invoices, receipts, due dates, reminders and aging balances.',
    path: '/finance-customers',
    icon: '🧑‍💼',
  },
  {
    id: 'finance-suppliers',
    title: 'Fournisseurs',
    description: 'Supplier accounting: invoices, payments, retentions and due dates.',
    path: '/finance-suppliers',
    icon: '🏭',
  },
  {
    id: 'finance-budgets',
    title: 'Budgets',
    description: 'Budget versions, forecasts, actuals, variances, revisions and simulations.',
    path: '/finance-budgets',
    icon: '📊',
  },
  {
    id: 'management-control',
    title: 'Contrôle de gestion',
    description: 'Cost centers, profitability, KPI variance analysis and financial steering.',
    path: '/management-control',
    icon: '🎯',
  },
  {
    id: 'human-resources',
    title: 'Ressources Humaines',
    description: 'Enterprise HR, payroll and workforce management workspace.',
    path: '/human-resources',
    icon: '👥',
  },
  {
    id: 'employees',
    title: 'Employes',
    description: 'Employee records, roles, assignments and lifecycle.',
    path: '/employees',
    icon: '🧑',
  },
  {
    id: 'organization',
    title: 'Organisation',
    description: 'Org structure, reporting lines and headcount planning.',
    path: '/organization',
    icon: '🏢',
  },
  {
    id: 'hr-contracts',
    title: 'Contrats RH',
    description: 'Workforce contracts, terms, status and renewal tracking.',
    path: '/hr-contracts',
    icon: '📄',
  },
  {
    id: 'payroll',
    title: 'Paie',
    description: 'Payroll preparation, validation, settlement and controls.',
    path: '/payroll',
    icon: '💸',
  },
  {
    id: 'attendance',
    title: 'Presences',
    description: 'Attendance, overtime and field workforce tracking.',
    path: '/attendance',
    icon: '🕒',
  },
  {
    id: 'leaves',
    title: 'Conges',
    description: 'Leave requests, approvals, balances and planning.',
    path: '/leaves',
    icon: '🌴',
  },
  {
    id: 'skills',
    title: 'Competences',
    description: 'Skills matrix, certifications and competency gaps.',
    path: '/skills',
    icon: '🧠',
  },
  {
    id: 'trainings',
    title: 'Formations',
    description: 'Training plans, sessions, participants and budgets.',
    path: '/trainings',
    icon: '🎓',
  },
  {
    id: 'recruitment',
    title: 'Recrutement',
    description: 'Hiring pipeline, candidate funnel and staffing needs.',
    path: '/recruitment',
    icon: '🧲',
  },
  {
    id: 'evaluations',
    title: 'Evaluations',
    description: 'Performance reviews, potential assessment and plans.',
    path: '/evaluations',
    icon: '📈',
  },
  {
    id: 'prompt-studio',
    title: 'Prompt Studio',
    description: 'Build and refine prompts for your agents.',
    path: '/prompt-studio',
    icon: '🎯',
  },
  {
    id: 'prompt-templates',
    title: 'Prompt Templates',
    description: 'Manage reusable template library and publishing workflows.',
    path: '/prompt-templates',
    icon: '🧩',
  },
  {
    id: 'generate',
    title: 'Generate',
    description: 'Create content and code with AI.',
    path: '/generate',
    icon: '✨',
  },
  {
    id: 'providers',
    title: 'Providers',
    description: 'Configure AI providers and endpoints.',
    path: '/providers',
    icon: '🔌',
  },
  {
    id: 'history',
    title: 'History',
    description: 'Track past requests and outputs.',
    path: '/history',
    icon: '🕘',
  },
  {
    id: 'observability',
    title: 'Observability',
    description: 'Monitor logs, metrics, and diagnostics.',
    path: '/observability',
    icon: '📈',
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Customize your workspace and preferences.',
    path: '/settings',
    icon: '⚙️',
  },
  {
    id: 'administration',
    title: 'Administration',
    description: 'Manage access, security, and governance.',
    path: '/administration',
    icon: '🛡️',
  },
]
