/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as KnowledgeCenterRouteImport } from './routes/knowledge-center'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptStudioRouteImport } from './routes/prompt-studio'
import { Route as PromptTemplatesRouteImport } from './routes/prompt-templates'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCenterRoute = KnowledgeCenterRouteImport.update({
  id: '/knowledge-center',
  path: '/knowledge-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptStudioRoute = PromptStudioRouteImport.update({
  id: '/prompt-studio',
  path: '/prompt-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptTemplatesRoute = PromptTemplatesRouteImport.update({
  id: '/prompt-templates',
  path: '/prompt-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/knowledge-center': typeof KnowledgeCenterRoute
  '/observability': typeof ObservabilityRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/prompt-templates': typeof PromptTemplatesRoute
  '/providers': typeof ProvidersRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/knowledge-center': typeof KnowledgeCenterRoute
  '/observability': typeof ObservabilityRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/prompt-templates': typeof PromptTemplatesRoute
  '/providers': typeof ProvidersRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/knowledge-center': typeof KnowledgeCenterRoute
  '/observability': typeof ObservabilityRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/prompt-templates': typeof PromptTemplatesRoute
  '/providers': typeof ProvidersRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/administration'
    | '/agents'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/generate'
    | '/history'
    | '/knowledge-center'
    | '/observability'
    | '/profile'
    | '/projects'
    | '/prompt-studio'
    | '/prompt-templates'
    | '/providers'
    | '/reviews'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/administration'
    | '/agents'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/generate'
    | '/history'
    | '/knowledge-center'
    | '/observability'
    | '/profile'
    | '/projects'
    | '/prompt-studio'
    | '/prompt-templates'
    | '/providers'
    | '/reviews'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/administration'
    | '/agents'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/generate'
    | '/history'
    | '/knowledge-center'
    | '/observability'
    | '/profile'
    | '/projects'
    | '/prompt-studio'
    | '/prompt-templates'
    | '/providers'
    | '/reviews'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdministrationRoute: typeof AdministrationRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  GenerateRoute: typeof GenerateRoute
  HistoryRoute: typeof HistoryRoute
  KnowledgeCenterRoute: typeof KnowledgeCenterRoute
  ObservabilityRoute: typeof ObservabilityRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptStudioRoute: typeof PromptStudioRoute
  PromptTemplatesRoute: typeof PromptTemplatesRoute
  ProvidersRoute: typeof ProvidersRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-center': {
      id: '/knowledge-center'
      path: '/knowledge-center'
      fullPath: '/knowledge-center'
      preLoaderRoute: typeof KnowledgeCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-studio': {
      id: '/prompt-studio'
      path: '/prompt-studio'
      fullPath: '/prompt-studio'
      preLoaderRoute: typeof PromptStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-templates': {
      id: '/prompt-templates'
      path: '/prompt-templates'
      fullPath: '/prompt-templates'
      preLoaderRoute: typeof PromptTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdministrationRoute: AdministrationRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  GenerateRoute: GenerateRoute,
  HistoryRoute: HistoryRoute,
  KnowledgeCenterRoute: KnowledgeCenterRoute,
  ObservabilityRoute: ObservabilityRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  PromptStudioRoute: PromptStudioRoute,
  PromptTemplatesRoute: PromptTemplatesRoute,
  ProvidersRoute: ProvidersRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
